use std::fmt::{Display, Formatter};

/// An enum providing all possible errors generated by this crate.
#[derive(Debug)]
pub enum Error {
    /// Thrown when a string with invalid data is attempted to be parsed into
    /// an identifier.
    InvalidData,

    /// The provided prefix contains invalid characters or is the wrong length.
    InvalidPrefix,

    /// The provided input is in an invalid format.
    InvalidFormat,

    /// Thrown when a string containing an invalid character is attempted to
    /// be pasrsed into an identifier.
    InvalidChar,

    /// Thrown when a string of invalid length is attempted to be parsed into
    /// an identifier.
    InvalidLength,
}

impl Display for Error {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}

impl std::error::Error for Error {}
